# Generated by Django 4.0.1 on 2022-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментария', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d?'),
        ),
    ]
